version: '3'

services:
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower:latest
    environment:
      - WATCHTOWER_NOTIFICATIONS=slack
      - WATCHTOWER_NOTIFICATION_SLACK_HOOK_URL="https://discord.com/api/webhooks/816433077383069737/s1xaLrwuwi0vqTKlhN1xPKhMMGzah6n7GoQocnmlcramrvygaPg2mqRnAqQmYpP8UanA/slack"

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 8080:8080
    command: --interval 10 androbot --notifications slack --notification-slack-hook-url https://discord.com/api/webhooks/816433077383069737/s1xaLrwuwi0vqTKlhN1xPKhMMGzah6n7GoQocnmlcramrvygaPg2mqRnAqQmYpP8UanA/slack
  androbot:
    container_name: androbot
    image: devksingh4/androbot:latest
    restart: always
    environment:
      - DISCORD_TOKEN
      - PREFIX=?
      - ACTIVITY=?help
    volumes:
      - ./saved/:/usr/src/app/commands/music/saved
