version: '3'

services:
  androbot:
    image: devksingh4/androbot:latest
    restart: on-failure
    environment:
      - DISCORD_TOKEN
      - PREFIX="?"
      - ACTIVITY="<help"
    volumes:
      - ./saved/:/usr/src/app/commands/musics/saved/
