version: '3'

services:
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 8080:8080
    command: --interval 10 --http-api-metrics --http-api-token androbot --debug androbot
  androbot:
    image: devksingh4/androbot:latest
    restart: always
    environment:
      - DISCORD_TOKEN
      - PREFIX=?
      - ACTIVITY=?help
    volumes:
      - ./saved/:/usr/src/app/commands/musics/saved/
